apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-registeroppslag
  namespace: teampam
  labels:
    team: teampam
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 40
  readiness:
    path: /internal/isReady
    initialDelay: 40
  replicas:
    min: {{ min_replicas }}
    max: {{ max_replicas }}
    scalingStrategy:
      cpu:
        thresholdPercentage: 50
  resources:
    limits:
      cpu: 1000m
      memory: 1536Mi
    requests:
      cpu: 20m
      memory: 384Mi
  secureLogs:
    enabled: true
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
      enabled: true
  leaderElection: true
  prometheus:
    enabled: true
    path: /internal/prometheus
  ingresses:
  {{#each ingress as |url|}}
     - {{url}}
  {{/each}}
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      tenant: {{ azure_ad_tenant }}
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
  valkey:
    - instance: registeroppslag
      access: readwrite
  accessPolicy:
    outbound:
      external:
        - host: "registerdata.arbeidstilsynet.no"
        - host: "data.arbeidstilsynet.no"
  env:
    - name: VALKEY_USE_TLS
      value: "true"
    - name: BEMANNINGSFORETAKSREGISTER_URL
      value: "https://data.arbeidstilsynet.no/bemanningsforetaksregisteret2/api/virksomheter"

