apiVersion: "monitoring.coreos.com/v1"
kind: "PrometheusRule"
metadata:
  name: "pam-registeroppslag-alerts"
  namespace: "teampam"
  labels:
    team: "teampam"
spec:
  groups:
    - name: "teampam pam-registeroppslag alerts"
      rules:
        - alert: Feil i nedlasting av bemanningsforetaksregisteret
          expr: sum(changes(pam_registeroppslag_nedlasting_bemanningsforetak_total[1d])) < 1
          for: 1h
          labels:
            severity: danger
            namespace: teampam
            teampam_alert_type: team_stilling_alert
            alert_type: custom
          annotations:
            summary: "Har ikke lastet ned enheter fra bemanningsforetaksregisteret siste døgn"
            action: "Sjekk i loggene om det er feil i nedlastingen (https://logs.adeo.no/app/r/s/uLp3a)"