name: Deploy alerts to NAIS prod-gcp
on:
  push:
    branches:
      - main
    paths:
      - 'naiserator-alerts.yml'
      - 'alerts-prod.yml'
jobs:
  apply-alerts:
    name: Apply alerts to prod
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: deploy to prod
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: naiserator-alerts.yml
