name: Deploy alerts to NAIS dev-gcp
on:
  push:
    branches:
      - '**'
    paths:
      - 'naiserator-alerts.yml'
      - 'alerts-dev.yml'
jobs:
  apply-alerts:
    name: Apply alerts to dev
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: deploy to dev
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: naiserator-alerts.yml
